### PR TITLE
Logging: Default Global Exception Handler and Standardized Legacy Logging

### PR DESCRIPTION
**Pull request by Windchild292**
MegaMekLab side of https://github.com/MegaMek/megamek/pull/3346

### CODE REVIEW

**Comment by SJuliez** [comment]
Interesting. Does this affect the AWT event thread? I'd expect exceptions to mostly happen there.

**Comment by Windchild292** [comment]
I tested using AWT, for exactly that reason. Plus it's a thread we don't directly control, which ensures that it holds across the system.

With AWT Exceptions it won't do the graphical display, but does properly log the exception to the primary log file (MegaMekLab.log for MML).

**Comment by Windchild292** [comment]
image

**Comment by Windchild292** [comment]
I will be watching the legacy log though, to ensure everything is caught. Once I'm done converting the remaining legacy logging to the log manager I'll remove the clearing functionality, and hopefully we will see an empty log from our constant dev version players. If those stay empty for a few releases, I'll know we can (finally) remove the old redirect.

**Review by SJuliez — APPROVED** [review]

**Comment by SJuliez** [comment]
Just for the record, I gave it a quick test by changing line 48 in MegaMekLabMainUI to
menubarcreator = new MenuBar(null);
(replace "this" with "null"). It just closed down MML without any dialog popping up. But the exception is still in the log file, so all in all I experienced no change.

**Comment by Windchild292** [comment]
It does log on the proper log file though, not the legacy one... right? If so, then it's still an improvement for that case

**Comment by SJuliez** [comment]
It appeared in megameklab.log. Is megameklablog.txt the legacy one then? (Sorry Im a bit oblivious there, I tend to comment out the logging to have exceptions in the console)

**Comment by Windchild292** [comment]
Legacy.log will be the new legacy logger, which is the console redirect. LogManager writes to MegaMekLab.log, so it's an improvement above the current and will help us remove our ancient logging redirect.

**Comment by Windchild292** [comment]
I've also sent you a Log4j2.xml file that will let you redirect to console going forwards.

**Pull request merged**
