### PR TITLE
Added the ability to select XCT specialization

### PR DESCRIPTION
**Pull request by pheonixstorm**
This should complete the addition of XCT troops into Megamek.

### CODE REVIEW

**Comment by HammerGS** [comment]
This is likely not ready to go. Since XCT needs sub-specialization.  Per this thread.

https://github.com/MegaMek/megamek/pull/493#issuecomment-286023060

I'm still waiting to hear back from Xotl for additional clarifications.

**Comment by Dylan-M** [comment]
Additionally, we need to know (if the thread doesn't already specify) whether or not infantry can be trained for multiple specializations. I would hope yes, and honestly I want this written for the yes answer regardless so that it's possible to override with an option to allow it if the rules say no.

**Comment by pheonixstorm** [comment]
From a coding standpoint I still think splitting XCT up isn't needed. You can't call a snowsuited XCT rated for Vacuum and expect them to survive. Doing so would require adding A LOT of XCT specs.

All
Cold Weather
Extreme Heat
Tainted Atmosphere
Toxic Atmosphere
Vacuum.
Hazardous Liquids

I can see wanting to get the rules right, but sometimes you just have to fudge things a bit to make it work. Its not done often, but it is done to make things work. Anyone else agree?

**Comment by Dylan-M** [comment]
No, I don't. I didn't say send snowsuited infantry that are also trained for vacuum operations into space in their snowsuits. If they can have multiple specializations, it also stands to ready they would have equipment for each specialization. If we ever start tracking infantry equipment, that will have to be dealt with. But, that should _never_ be a deterrent from doing it _right_. That attitude is why the code is such a cluster f... mess right now. I will not perpetuate that.

**Comment by pheonixstorm** [comment]
There is no equipment, it is all armor based. And that is something you can't change w/o putting the unit back in MML to swap out the armor from one kit to another

**Comment by Dylan-M** [comment]
Unless we make a provision from doing it via the context menu.
Change Infantry Armor -> Snowsuit
                                          Vac Suit
                                          etc...

This is easily do-able.

**Comment by pheonixstorm** [comment]
And save over the old blk or create a new one? I see where your thinking is but not sure how best to work the end result. Would MM take something like this from HQ or would you have to save/reload?

**Comment by Dylan-M** [comment]
It would be no different than how we currently track ammo for 'Mechs. Nothing gets saved to the actual unit file, it's tracked in the campaign file as a modification to the unit there.

**Comment by pheonixstorm** [comment]
Which code wise I have never looked into... Ok, will add all the specs to MM/MML.

**Pull request closed without merging**
