### PR TITLE
RFE #1156: make 'auto fill unhittables' and 'auto compact' saveable o…

### PR DESCRIPTION
**Pull request by Sleet01**
…ption

Problem:

  Some users want to turn off Auto Fill Unhittables and Auto Compact by
default, so that they can assign all criticals directly without having to reset or move auto-assigned items.

Solution:

  1. Add two new checkboxes to Misc Settings Panel for these options. A. Both are enabled by default. B. Both have suitable text and tooltips describing functionality.
  2. Have BMBuildTab read these CConfig values when instantiating the relevant buttons.

Testing:

  1. Tested new options: Checkboxes can be set/unset, saved, and loaded correctly.
  2. Tested with new Meks; default HS and added unhittable items are not filled or compacted.
  3. Tested with loaded mechs; changed items are not filled or compacted.

### CODE REVIEW

**Comment by SJuliez** [comment]
Oooooh as it has to happen at some point, I did the same but have not yet made a PR of it. Now what I did differently is that the offending buttons themselves simply save their state whenever clicked. So when disabling one of them, it'll stay disabled when loading the next mek. Seems simpler than having it in the options? I'll make a PR shortly, then we can see which one to use :)

**Comment by Sleet01** [comment]
> Oooooh as it has to happen at some point, I did the same but have not yet made a PR of it. Now what I did differently is that the offending buttons themselves simply save their state whenever clicked. So when disabling one of them, it'll stay disabled when loading the next mek. Seems simpler than having it in the options? I'll make a PR shortly, then we can see which one to use :)

The specific request in the RFE was for a saveable setting that would persist, so that's what I did.

**Comment by SJuliez** [comment]
My solution also persists. I did the same in Cconfig.

**Comment by HammerGS** [comment]
@Sleet01 thansk for the PR much appreciated. 

But to me something that automatically remembers a setting is a better option.

**Comment by Sleet01** [comment]
Sounds like the other PR is preferred; closing.

**Pull request closed without merging**
